name: Reset Workspace Ownership Action
description: A GitHub Action to reset ownership of the files not owned by the Actions runner in the workspace directory

inputs:
  user_id:
    description: The user id to change the owner to when not matched
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.user }}
    - ${{ github.workspace }}

branding:
  icon: user-check
  color: yellow