name: Test self-hosted

on:
  workflow_dispatch:

jobs:
  test:
    name: Test

    runs-on: self-hosted

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Invoke Action
        uses: peter-murray/reset-permissions-action@main
        
