name: Test self-hosted

on:
  workflow_dispatch:

jobs:
  test:
    name: Test

    runs-on: self-hosted

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get Actions user id
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo ::set-output name=uid::$actions_user_id

      - name: Invoke Action
        uses: peter-murray/reset-permissions-action@main
        with:
          user_id: ${{ steps.get_uid.outputs.uid }}
        
